name: Build Docker Image
on:
  pull_request:
    branches:
      - "master/**"
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: openhack37d5bau5acr.azurecr.io
        repository: devopsoh/api-userprofile
        dockerfile: userprofile/Dockerfile
        tag_with_sha: true
        push: false