name: Build Docker Image
on:
  workflow_dispatch:
    paths:
      - apis/userprofile/*

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Github
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build and Push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        cd ${GITHUB_WORKSPACE}/apis/userprofile
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/devopsoh/api-userprofile:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}
    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }}
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GIT_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
