name: Build Docker Image
on:
#  pull_request:
#    branches:
#      - "master/**"
  push:
    branches:
      - '**'
    paths:
      - apis/userprofile/*
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: openhack37d5bau5acr.azurecr.io
        repository: devopsoh/api-userprofile
        dockerfile: apis/userprofile/Dockerfile_removethis
        tag_with_sha: true
        push: false
    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GIT_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
