name: CD-Test
on:
  workflow_dispatch:

jobs:
  git_checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    name: Checkout Github
  build_image:
    runs-on: ubuntu-latest
    needs: git_checkout
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build and Push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        REPO_NAME=${{ secrets.REPO_NAME }}

        echo "building userprofile"
        cd ${GITHUB_WORKSPACE}/apis/userprofile
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-userprofile:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}



  deployment_test:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Deploy userprofile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack37d5bau5userprofile'
          images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REPO_NAME }}/api-userprofile:${{ github.sha }}'

