name: build-services-from-master
on:
  push:
    branches:
      - 'master'
    paths:
      - apis/**

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Github
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build and Push Docker image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        REPO_NAME=devopsoh

        echo "building userprofile"
        cd ${GITHUB_WORKSPACE}/apis/userprofile
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-userprofile:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}

        echo "building poi"
        cd ${GITHUB_WORKSPACE}/apis/poi/web
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-poi:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}

        echo "building trips"
        cd ${GITHUB_WORKSPACE}/apis/trips
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-trips:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}

        echo "building user-java"
        DOCKER_IMAGE=${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-user-java:${{ github.sha }}
        docker build . -t ${DOCKER_IMAGE}
        docker push ${DOCKER_IMAGE}

    - name: Deploy userprofile
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack37d5bau5userprofile'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-userprofile:${{ github.sha }}'
    - name: Deploy poi
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack37d5bau5poi'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-poi:${{ github.sha }}'
    - name: Deploy trips
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack37d5bau5trips'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-trips:${{ github.sha }}'
    - name: Deploy user-java
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhack37d5bau5userjava'
        images: '${{ secrets.REGISTRY_LOGIN_SERVER }}/${REPO_NAME}/api-user-java:${{ github.sha }}'

    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }}
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GIT_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}
